# site settings
title: Converge 
subtitle: Consulting
email: hello@convergeconsulting.com
description: Weaving technology through human experience
baseurl: "/converge-consulting.jp" # the subpath of your site, e.g. /blog
url: "s3-ap-northeast-1.amazonaws.com" # the base hostname & protocol for your site
author:
street_address: 
city: Meguro
state: Tokyo
zip_code: 153-0052
country: Japan 
Phone: 617-299-9022

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
